// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIpo7imBjc7wGyUF8dPLPkqwqPBQqn1s',
    appId: '1:300049256813:web:c8077eccb1f5d51bd20a64',
    messagingSenderId: '300049256813',
    projectId: 'musicfinder-fc3f2',
    authDomain: 'musicfinder-fc3f2.firebaseapp.com',
    storageBucket: 'musicfinder-fc3f2.appspot.com',
    measurementId: 'G-4JTLKGM29J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4peYOb7iC-D0vwqP6cKC5cUhdLYpAWG4',
    appId: '1:300049256813:android:86b8231f296049efd20a64',
    messagingSenderId: '300049256813',
    projectId: 'musicfinder-fc3f2',
    storageBucket: 'musicfinder-fc3f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGVKjEwiBMHad4tBIDSWes7MeTW1ywBbc',
    appId: '1:300049256813:ios:fdb532fb6aec6f7fd20a64',
    messagingSenderId: '300049256813',
    projectId: 'musicfinder-fc3f2',
    storageBucket: 'musicfinder-fc3f2.appspot.com',
    iosClientId: '300049256813-v9403luubu3c0k3skkkflq0mrk7jognd.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGVKjEwiBMHad4tBIDSWes7MeTW1ywBbc',
    appId: '1:300049256813:ios:fdb532fb6aec6f7fd20a64',
    messagingSenderId: '300049256813',
    projectId: 'musicfinder-fc3f2',
    storageBucket: 'musicfinder-fc3f2.appspot.com',
    iosClientId: '300049256813-v9403luubu3c0k3skkkflq0mrk7jognd.apps.googleusercontent.com',
    iosBundleId: 'com.example.practica1',
  );
}
